### PR TITLE
Manage setuptools with cfg file

### PR DESCRIPTION
**Pull request by 4383**
Hello

### Overview
Using setuptools setup.cfg for configuring project. 
Introduced by setuptools latest version.

### Features
- dynamical version from package or config file
- move setuptools config to setup.cfg
- using python entrypoints insteadof `bin/bleemeo-agent*` keep sh entrypoints in `bin`

### CODE REVIEW

**Comment by PierreF** [comment]
Hi,

thanks for your PR. I would like to merge this PR but this currently this break our build chain. We build native package for Ubuntu and CentOS, both of them have too old setuptools to understand setup.cfg.

We must find a way to build on those OS before merging this PR. I'll look if creating a backport for setuptools is doable.

**Comment by 4383** [comment]
@PierreF do you need some help?
I can see you use docker containers specialized into packaging formats (rpm, deb, etc...) I already have create somes images containers like this on private projects so I can easily understand your problems.
I think you just need to update setuptools in your containers:
```
$ pip install -U setuptools
```
Do not hesitate to ask some help to me :)

**Comment by 4383** [comment]
Example on this `build/02-build-package-rpm`.

If I considere pip is already installed in your docker image you do not have to update your image.
You can just update the run command with this:
```
docker run --rm \
    -v $(pwd):/srv/workspace -w /srv/workspace \
    bleemeo/centos-pkg-builder sh -ec '
pip install -U setuptools
cp -v bleemeo-agent_*.tar /root/rpmbuild/SOURCES/
cp -v bleemeo-agent-*/packaging/centos/bleemeo-agent.spec /root/rpmbuild/SPECS/
rpmbuild -bs /root/rpmbuild/SPECS/bleemeo-agent.spec
cp /root/rpmbuild/SRPMS/bleemeo-agent-*.src.rpm .'
```
If pip is not already installed you need to update your docker image... (`yum install pip`).

**Comment by PierreF** [comment]
Sadly our Docker image are only used to have mock/pbuilder. The build itself is done using those tools, so the pip install -U would be needed inside the chroot created by them.
Also using a pip install -U would means that native source package (.src.rpm or .dsc) would become harder to rebuild by third-party.
Creating backport package for setuptools would be better as is won't break existing state but require more work. Currently I don't known how much additional work is needed for backport and (depending on how much) if it worse going this way instead of a simple pip install -U.

**Comment by 4383** [comment]
@PierreF I've introduce a little change, now I retrieve version from `__init__.py` inside `setup.cfg`.
This change introduce a more secure retrieving, indeed, I remove possible problems when we try to retrieve version on environment where bleemeo-agent is already installed.

**Comment by PierreF** [comment]
On my side, I've made progress on backporting setuptools. I've a working version for Ubuntu (trusty - our older supported version).
I'm working on CentOS 7 backport.

**Comment by PierreF** [comment]
Backports done, build with backported setuptools works. Thanks for your patience.

**Comment by 4383** [comment]
With pleasure!

Thank you for your efforts in integrating my changes.

**Pull request merged**
